Project/FastForward.WebAbansToursNew/FastForward.WebAbansTours/Controllers/InvoicingController.cs
using CrystalDecisions.CrystalReports.Engine;
using FastForward.WebAbansTours.Models;
using FF.BusinessObjects;
using FF.BusinessObjects.Tours;
using FF.BusinessObjects.ToursNew;
using FF.Resources;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Security.Authentication;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace FastForward.WebAbansTours.Controllers
{
    public class InvoicingController : BaseController
    {
        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            string userId = HttpContext.Session["UserID"] as string;
            string company = HttpContext.Session["UserCompanyCode"] as string;
            string userDefPro = HttpContext.Session["UserDefProf"] as string;
            string userDefLoc = HttpContext.Session["UserDefLoca"] as string;
            if (!string.IsNullOrEmpty(userId) && !string.IsNullOrEmpty(company) && !string.IsNullOrEmpty(userDefPro) && !string.IsNullOrEmpty(userDefLoc))
            {
                ST_MENU per = CHNLSVC.Tours.getAcccessPermission(userId, 1019);
                if (per.MNU_ID == 0)
                {
                    throw new AuthenticationException("You do not have the necessary permission to perform this action");
                }
            }
            else
            {
                Redirect("~/Login/index");
            }

        }
        // GET: Invoicing

        List<InvoiceItem> oMainItemsList;
        List<RecieptItem> _recieptItem;
        List<MST_ST_PAX_DET> paxDetList;
        private InvoiceHeader oHeader = null;
        public ActionResult Index(string enqid, string cuscd, string address, string mobile)
        {
            string userId = HttpContext.Session["UserID"] as string;
            string company = HttpContext.Session["UserCompanyCode"] as string;
            string userDefPro = HttpContext.Session["UserDefProf"] as string;
            string userDefLoc = HttpContext.Session["UserDefLoca"] as string;
            string date = DateTime.Today.Date.ToString();
            string[] tokens = date.Split(' ');
            if (!string.IsNullOrEmpty(userId) && !string.IsNullOrEmpty(company) && !string.IsNullOrEmpty(userDefPro) && !string.IsNullOrEmpty(userDefLoc))
            {
                ViewBag.date = tokens[0];
                Session["oMainItemsList"] = null;
                Session["_recieptItem"] = null;
                Session["RecieptItemList"] = null;
                Session["totalPaidAmount"] = null;
                Session["paxDetList"] = null;
                Session["oHeader"] = null;
                if (enqid != null && cuscd != null)
                {
                    ViewBag.enqid = enqid;
                    ViewBag.cuscd = cuscd;
                    ViewBag.address = address;
                    ViewBag.mobile = mobile;

                    List<InvoiceHeader> InvData = CHNLSVC.Tours.GetInvoiceData(enqid);
                    var invNo = InvData.Where(b => b.Sah_stus == "A" && b.Sah_direct == true).Max(a => a.Sah_inv_no);
                    ViewBag.InvNo = invNo;
                }
                string InvId = HttpContext.Session["InvNo"] as string;
                if (InvId != "") ViewBag.InvId = InvId;
                Session["InvNo"] = null;

                return View();
            }
            else
            {
                return Redirect("~/Login/index");
            }
        }

        public JsonResult getCostSheetData(string enqid)
        {
            string userId = HttpContext.Session["UserID"] as string;
            string company = HttpContext.Session["UserCompanyCode"] as string;
            string userDefPro = HttpContext.Session["UserDefProf"] as string;
            string userDefLoc = HttpContext.Session["UserDefLoca"] as string;

            string err;

            if (!string.IsNullOrEmpty(userId) && !string.IsNullOrEmpty(company) && !string.IsNullOrEmpty(userDefPro) && !string.IsNullOrEmpty(userDefLoc))
            {

                QUO_COST_HDR oCostHeader = null;
                List<QUO_COST_DET> oCostMainItems = null;

                Int32 result = CHNLSVC.Tours.getCostSheetDetails(Session["UserCompanyCode"].ToString(), Session["UserDefProf"].ToString(), enqid, "3", out oCostHeader, out oCostMainItems, out err);
                //ViewBag.oCostMainItems = oCostMainItems;
                return Json(new { success = true, login = true, data = oCostMainItems }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, login = false }, JsonRequestBehavior.AllowGet);
            }

        }
        public JsonResult getEnquiryCharges(string enqid)
        {
            string userId = HttpContext.Session["UserID"] as string;
            string company = HttpContext.Session["UserCompanyCode"] as string;
            string userDefPro = HttpContext.Session["UserDefProf"] as string;
            string userDefLoc = HttpContext.Session["UserDefLoca"] as string;

            string err;

            if (!string.IsNullOrEmpty(userId) && !string.IsNullOrEmpty(company) && !string.IsNullOrEmpty(userDefPro) && !string.IsNullOrEmpty(userDefLoc))
            {
                List<ST_ENQ_CHARGES> oCostMainItems = CHNLSVC.Tours.tempEnquiryCharges(enqid);
                oCostMainItems = oCostMainItems.Where(a => a.SCH_INVOICED == 0).ToList();
                return Json(new { success = true, login = true, data = oCostMainItems }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, login = false }, JsonRequestBehavior.AllowGet);
            }

        }
        public ActionResult InvoiceCreate(InvoiceHeader inv)
        {
            string userId = HttpContext.Session["UserID"] as string;
            string company = HttpContext.Session["UserCompanyCode"] as string;
            string userDefPro = HttpContext.Session["UserDefProf"] as string;
            string userDefLoc = HttpContext.Session["UserDefLoca"] as string;
            if (!string.IsNullOrEmpty(userId) && !string.IsNullOrEmpty(company) && !string.IsNullOrEmpty(userDefPro) && !string.IsNullOrEmpty(userDefLoc))
            {
                MasterBusinessEntity _masterBusinessCompany = CHNLSVC.Sales.GetCustomerProfileByCom(inv.Sah_cus_cd, null, null, null, null, company);
                Session["Customer"] = _masterBusinessCompany;
                MasterBusinessEntity oCust = (MasterBusinessEntity)Session["Customer"];
                InvoiceHeader oHeader = new InvoiceHeader();
                oHeader.Sah_com = company;
                oHeader.Sah_cre_by = userId;
                oHeader.Sah_cre_when = DateTime.Now;
                oHeader.Sah_currency = "LKR";
                oHeader.Sah_cus_add1 = oCust.Mbe_add1;
                oHeader.Sah_cus_add2 = oCust.Mbe_add2;
                oHeader.Sah_cus_cd = oCust.Mbe_cd;
                oHeader.Sah_cus_name = oCust.Mbe_name;
                oHeader.Sah_d_cust_add1 = oCust.Mbe_add1;
                oHeader.Sah_d_cust_add2 = oCust.Mbe_add2;
                oHeader.Sah_d_cust_cd = oCust.Mbe_cd;
                oHeader.Sah_d_cust_name = oCust.MBE_FNAME;
                oHeader.Sah_direct = true;
                oHeader.Sah_dt = Convert.ToDateTime(inv.Sah_dt);
                oHeader.Sah_epf_rt = 0;
                oHeader.Sah_esd_rt = 0;
                oHeader.Sah_ex_rt = 1;
                oHeader.Sah_inv_no = "na";
                oHeader.Sah_inv_sub_tp = "SA";
                oHeader.Sah_inv_tp = inv.Sah_inv_tp;
                oHeader.Sah_is_acc_upload = false;
                oHeader.Sah_manual = false;
                oHeader.Sah_mod_by = userId;
                oHeader.Sah_mod_when = DateTime.Now;
                oHeader.Sah_pc = userDefPro;
                oHeader.Sah_pdi_req = 0;
                oHeader.Sah_ref_doc = Request["enq_id"];
                oHeader.Sah_sales_chn_cd = "";
                oHeader.Sah_sales_chn_man = "";
                oHeader.Sah_sales_ex_cd = inv.Sah_sales_ex_cd;
                oHeader.Sah_sales_region_cd = "";
                oHeader.Sah_sales_region_man = "";
                oHeader.Sah_sales_sbu_cd = "";
                oHeader.Sah_sales_sbu_man = "";
                oHeader.Sah_sales_str_cd = "";
                oHeader.Sah_sales_zone_cd = "";
                oHeader.Sah_sales_zone_man = "";
                oHeader.Sah_seq_no = 1;
                oHeader.Sah_session_id = Session["SessionID"].ToString();
                // oHeader.Sah_structure_seq = txtQuotation.Text.Trim();
                oHeader.Sah_stus = "A";
                //  if (chkDeliverLater.Checked == false || chkDeliverNow.Checked) oHeader.Sah_stus = "D";
                oHeader.Sah_town_cd = "";
                oHeader.Sah_tp = "INV";
                oHeader.Sah_wht_rt = 0;
                oHeader.Sah_direct = true;
                oHeader.Sah_tax_inv = inv.Sah_tax_inv;
                //oHeader.Sah_anal_11 = (chkDeliverLater.Checked || chkDeliverNow.Checked) ? 0 : 1;
                //oHeader.Sah_del_loc = (chkDeliverLater.Checked == false || chkDeliverNow.Checked) ? BaseCls.GlbUserDefLoca : !string.IsNullOrEmpty(txtDelLocation.Text) ? txtDelLocation.Text : string.Empty;
                oHeader.Sah_del_loc = string.Empty;
                //oHeader.Sah_grn_com = _customerCompany;
                //oHeader.Sah_grn_loc = _customerLocation;
                //oHeader.Sah_is_grn = _isCustomerHasCompany;
                //oHeader.Sah_grup_cd = string.IsNullOrEmpty(txtGroup.Text.Trim()) ? string.Empty : txtGroup.Text.Trim();
                //   oHeader.Sah_is_svat = lblSVATStatus.Text == "Available" ? true : false;
                //  oHeader.Sah_tax_exempted = lblExemptStatus.Text == "Available" ? true : false;

Project/FastForward.WebAbansToursNew/FastForward.WebAbansTours/Views/Home/Index.cshtml
@model PagedList.IPagedList<FF.BusinessObjects.GEN_CUST_ENQ>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Home Page";
    var val = System.Web.Configuration.WebConfigurationManager.AppSettings["SiteVersion"].ToString();
    string pc = (string)Session["UserDefProf"];
    var hidefields = System.Web.Configuration.WebConfigurationManager.AppSettings[pc];
    if (hidefields == null)
    {
        hidefields = "false";
    }
}
<link href="~/Content/PagedList.css?@val" rel="stylesheet" type="text/css" />
@section Scripts {
    <script src="~/Scripts/Common/Home.js?@val"></script>
}


@using (Html.BeginForm(new { @class = "form-horizontal" }))
{
    <div class="row">
        <div class="col-md-6">
            <p class="col-md-6">
                @Html.DropDownList("SearchField", new List<SelectListItem>() {
              new SelectListItem() {
                  Text = "System ID",
                  Value = "SysId"
              },
              new SelectListItem() {
                  Text = "Customer Id",
                  Value = "CusId"
              },
              new SelectListItem() {
                  Text = "Customer Name",
                  Value = "Name"
              },
              new SelectListItem() {
                  Text = "Mobile",
                  Value = "Mob"
              },
              new SelectListItem() {
                  Text = "Requested Date",
                  Value = "reqDte"
              },
              new SelectListItem() {
                  Text = "Expected Date",
                  Value = "expDte"
              }
          }, "-- Select Field --", new { @class = "form-control" })
            </p>
            <p class="col-md-6">
                @Html.Editor("SearchString", new { htmlAttributes = new { @class = "form-control with-search" } })
                <input type="submit" value="Search" class="btn btn-info btn-xs" />
            </p>
        </div>
    </div>
}





<div class="row enq-tracker-tbl">

    <table class="table table-striped table-hover pending-all-enq">
        <tr class="enq-hed">
            <th>System ID</th>
            <th>Request Type</th>
            <th>Customer Id</th>
            <th>Name</th>

            <th>Requested Date</th>

            <th>Mobile</th>
            <th>Expected Date</th>
            <th>Pending Days</th>
            <th>Enquiry</th>
            @if (ViewBag.perInvoice != 0) {
            <th>Status</th>
            }
            @if (ViewBag.perCosting != 0)
            { 
            <th>Go to Costing</th>
            }
            @if (ViewBag.perQuotation != 0)
            {
                <th>Go to Quotation</th>
            }
            @if (ViewBag.perInvoice != 0) { 
            <th>Go to Invoice</th>
            }
            <th>Documents</th>
            @{
                if (hidefields == "true")
                {
                    <th>Aggrement</th>
                }
            }
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GCE_ENQ_ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MET_DESC)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GCE_CUS_CD)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GCE_NAME)
                </td>


                <td>@String.Format("{0:d}", item.GCE_DT)</td>

                <td>
                    @Html.DisplayFor(modelItem => item.GCE_MOB)
                </td>
                <td>@String.Format("{0:d}", item.GCE_EXPECT_DT)</td>
                @if (@item.MES_DESC == "Invoiced" | @item.MES_DESC == "Cancelled")
                {
                    <td>Processed</td>
                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.PendingDate)
                    </td>
                }


                <td class="text-align-cls"><a class="popup-enq-ser" data-enq-id="@item.GCE_ENQ_ID" data-enq-rem="@item.GCE_ENQ"><img data-toggle="modal" data-target="#myModalenqnew" src="~/Resources/Images/Info.png"></a></td>
                @if (ViewBag.perInvoice != 0) {
                <td>@item.MES_DESC</td>
                }
                @if(ViewBag.perCosting != 0){
                    if (@item.GCE_STUS == 5 || @item.GCE_STUS == 0)
                    {
                        <td class="text-align-cls"><span class="glyphicon glyphicon-remove-sign" style="font-size:large;color:#989393"></span></td>
                    }
                    else
                    {

                        <td class="text-align-cls"><a href="@Url.Action("Index","CostingSheet", new { enqid=@item.GCE_ENQ_ID })"><img src="~/Resources/Images/costing.png"></a></td>
                    }
                }
                
                @if ( ViewBag.perQuotation != 0)
                {
                    if (@item.GCE_STUS == 5 || @item.GCE_STUS == 0)
                    {
                        <td class="text-align-cls"><span class="glyphicon glyphicon-remove-sign" style="font-size:large;color:#989393"></span></td>
                    }
                    else
                    {

                        <td class="text-align-cls"><a href="@Url.Action("Index","Quotation", new { enqid=@item.GCE_ENQ_ID })"><img src="~/Resources/Images/costing.png"></a></td>
                    }
                }
                @if (ViewBag.perInvoice != 0) { 
                if (@item.GCE_STUS == 5 || @item.GCE_STUS == 12 || @item.GCE_STUS == 13)
                {
                    <td class="text-align-cls"> <a href="@Url.Action("Index","Invoicing", new { enqid=@item.GCE_ENQ_ID,cuscd=@item.GCE_CUS_CD,address=@item.GCE_ADD1,mobile=@item.GCE_MOB })"><img src="~/Resources/Images/invoice.png"></a></td>
                }
                else
                {
                    <td class="text-align-cls"><span class="glyphicon glyphicon-remove-sign" style="font-size:large;color:#989393"></span></td>
                }
                }
                <td class="text-align-cls "><a class="documents-uploads-process" href="#" data-enq-id="@item.GCE_ENQ_ID"><span class="glyphicon glyphicon-upload" data-toggle="modal" data-target="#myImageUploadModal" style="font-size:large;color:#989393"></span></a></td>
                @{
            if (hidefields == "true")
            {
                if (@item.GCE_ENQ_TP == "TNSPT")
                {
                    @*<td class="text-align-cls"> <a href="@Url.Action("Aggrement", "Home", new { enqid = @item.GCE_ENQ_ID, cuscd = @item.GCE_CUS_CD, address = @item.GCE_ADD1, mobile = @item.GCE_MOB })"><span class="glyphicon glyphicon-print" style="color:green;font-size:large"></span></a></td>*@
                    <td class="text-align-cls"><a href="/Home/Aggrement?EnqID=@item.GCE_ENQ_ID" target="_blank"><span class="glyphicon glyphicon-print" style="color:green;font-size:large"></span></a></td>

                }
                else
                {
                    <td class="text-align-cls"><span class="glyphicon glyphicon-print" style="font-size:large;color:#989393"></span></td>
                }
            }
                }

            </tr>
        }


    </table>
</div>

<div class="modal fade my-popup-div" id="myModalenqnew" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Custormer Enquiry Services</h4>
            </div>
            <div class="modal-body">
                <table class="table enqser-by-enqid">
                    <tr class="table-hed">
                        <th>Enq ID</th>
                        <th>Pick Town</th>
                        <th>Drop Town</th>
                        <th>Enquiry</th>
                    </tr>
                </table>
                <div class="enq-rem"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="pageination-footer home-page-paging">
    <div class="pageination-from">
        Page @ViewBag.Currentpage of @ViewBag.pagecount
    </div>
    <div class="pageination-page">
        @*@Html.PagedListPager(Model, page => Url.Action("Index", new { x }))*@
        @{
            var currentPage = ViewBag.Currentpage;
            var pagecutoff = 10;
            var prevPosition = currentPage - pagecutoff;
            var nextPosition = currentPage + pagecutoff;
            var count = 0;
            if (@ViewBag.pagecount >= 10)
            {
                count = 10;
            }
            else
            {
                count = @ViewBag.pagecount;
            }
            if (currentPage > count && count>0)
            {
                <a href="@Url.Action("Index", "Home", new { page = 1 })"><< </a>
                <a href="@Url.Action("Index", "Home", new { page = prevPosition })">< </a>
            }
            Int32 num = 0;
            if (count > 0)
            {
                Int32 start = currentPage / count;
                num = start * count + 1;
            }
            Int32 limit = num + count;
            if (limit > @ViewBag.pagecount)
            {
                limit = @ViewBag.pagecount;
            }
            for (var x = num; x <= limit; x++)
            {


                //if (x != currentPage)
                //{
                //    if (x >= prevPosition && x <= nextPosition)
                //    {
                //        var linkToPage = x == prevPosition ? currentPage - 1 : x == nextPosition ? currentPage + 1 : x;
                //     //   var linkText = x == prevPosition ? "<< prev" : x == nextPosition ? "next >>" :x;

                //        //pagingControls += "<li><a href='#' onclick='pager.showPage(" + linkToPage + "); return false;'>" + linkText + "</a></li>";
                //    }
                //}
                //else
                //{
                //    //pagingControls += "<li>" + i + "</li>";
                //}

                //if (x >= prevPosition && x <= nextPosition)
                //{

                //}
                //else
                //{
                if (count > 0) { 
                    if (x == currentPage)
                    {
                        <a class="active-page" href="@Url.Action("Index", "Home", new { page = x })">@x </a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index", "Home", new { page = x })">@x </a>
                    }
                }
                // }

            }
            if (currentPage != @ViewBag.pagecount && count>0)
            {
                var nextPage=nextPosition;
                if (nextPosition > @ViewBag.pagecount) {
                    nextPage = @ViewBag.pagecount;
                }
               <a href="@Url.Action("Index", "Home", new { page = nextPage })">></a>
                    <a href="@Url.Action("Index", "Home", new { page = @ViewBag.pagecount })">>></a>
            }
}
    </div>
</div>

<div class="modal fade" tabindex="-1" id="myImageUploadModal" role="dialog">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Documents</h4>
            </div>
            <div class="modal-body">
                @Html.Partial("~/Views/Shared/_ImageUploads.cshtml")
            </div>
            <div class="modal-footer" style="margin-top:120px">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

Project/FastForward.WebAbansToursNew/FastForward.WebAbansTours/Views/Home/Index2.cshtml
@model PagedList.IPagedList<FF.BusinessObjects.ToursNew.DriverAllocationHome>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Home Page";
    var val = System.Web.Configuration.WebConfigurationManager.AppSettings["SiteVersion"].ToString();
    string pc = (string)Session["UserDefProf"];
    var hidefields = System.Web.Configuration.WebConfigurationManager.AppSettings[pc];
    if (hidefields == null)
    {
        hidefields = "false";
    }
}
<link href="~/Content/PagedList.css?@val" rel="stylesheet" type="text/css" />
@section Scripts {
    <script src="~/Scripts/Common/Home.js?@val"></script>
}


@using (Html.BeginForm(new { @class = "form-horizontal" }))
{
    <div class="row">
        <div class="col-md-6">
            <p class="col-md-6">
                @Html.DropDownList("SearchField", new List<SelectListItem>() {
              new SelectListItem() {
                  Text = "Vehicle No",
                  Value = "Vehicle No"
              },
              new SelectListItem() {
                  Text = "Model",
                  Value = "Model"
              },
              new SelectListItem() {
                  Text = "Category",
                  Value = "Category"
              },
              new SelectListItem() {
                  Text = "System Id",
                  Value = "System Id"
              },
          }, "-- Select Field --", new { @class = "form-control" })
            </p>
            <p class="col-md-6">
                @Html.Editor("SearchString", new { htmlAttributes = new { @class = "form-control with-search" } })
                <input type="submit" value="Search" class="btn btn-info btn-xs" />
            </p>
        </div>
        @if (@ViewBag.Regexp=="true")
        {
              <div class="col-md-1">
            <p class="col-lg-12">
                <a class="fleet-alert-reg" href="#"><span class="glyphicon glyphicon-envelope" style="color:#cc1717;font-size:large"></span></a>
            </p>
        </div>
        }
        @if (@ViewBag.LisExp == "true")
        {
            <div class="col-md-1">
                <p class="col-lg-12">
                    <a class="fleet-alert-lis" href="#"><span class="glyphicon glyphicon-envelope" style="color:#550909;font-size:large"></span></a>
                </p>
            </div>
        }
    </div>
}

<div class="row enq-tracker-tbl">

    <table class="table table-striped table-hover pending-all-enq">
        <tr class="enq-hed">
            <th>Vehicle No</th>
            <th>Model</th>
            <th>Category</th>
            <th>Reservation No</th>
            <th>Starting Date</th>
            <th>Ending Date</th>
            <th>Reallocation</th>
            <th>Cancel</th>
            <th>SMS(Driver)</th>
            <th>SMS(Custormer)</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.mstf_regno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mstf_model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mstf_veh_tp)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.gce_enq_id)
                </td>
                <td>@String.Format("{0:d}", item.mfd_frm_dt)</td>
                <td>@String.Format("{0:d}", item.mfd_to_dt)</td>
                <td class="text-align-cls"><a href="/DriverAllocation/Index?EnqID=@item.mstf_regno"><span class="glyphicon glyphicon-book" style="font-size: large; color: green"></span></a></td>
                <td class="text-align-cls"><a href="/DriverAllocation/Index?EnqID=@item.mstf_regno"><span class="glyphicon glyphicon-remove" style="font-size: large; color: green"></span></a></td>
                <td class="text-align-cls"><a class="send-sms-driver" href="#" data-enq-id="@item.gce_enq_id"><span class="glyphicon glyphicon-comment" style="font-size: large; color: green"></span></a></td>
                <td class="text-align-cls"><a class="send-sms-cust" href="#" data-enq-id="@item.gce_enq_id"><span class="glyphicon glyphicon-comment" style="font-size: large; color: green"></span></a></td>
            </tr>
        }


    </table>
</div>
<div class="pageination-footer home-page-paging">
    <div class="pageination-from">
        Page @ViewBag.Currentpage of @ViewBag.pagecount
    </div>
    <div class="pageination-page">
        @*@Html.PagedListPager(Model, page => Url.Action("Index", new { x }))*@
        @{
            var currentPage = ViewBag.Currentpage;
            var pagecutoff = 10;
            var prevPosition = currentPage - pagecutoff;
            var nextPosition = currentPage + pagecutoff;
            var count = 0;
            if (@ViewBag.pagecount >= 10)
            {
                count = 10;
            }
            else
            {
                count = @ViewBag.pagecount;
            }
            if (currentPage > count && count > 0)
            {
                <a href="@Url.Action("Index2", "Home", new { page = 1 })"><< </a>
                <a href="@Url.Action("Index2", "Home", new { page = prevPosition })">< </a>
            }
            Int32 num = 0;
            if (count > 0)
            {
                Int32 start = currentPage / count;
                num = start * count + 1;
            }
            Int32 limit = num + count;
            if (limit > @ViewBag.pagecount)
            {
                limit = @ViewBag.pagecount;
            }
            for (var x = num; x <= limit; x++)
            {


                //if (x != currentPage)
                //{
                //    if (x >= prevPosition && x <= nextPosition)
                //    {
                //        var linkToPage = x == prevPosition ? currentPage - 1 : x == nextPosition ? currentPage + 1 : x;
                //     //   var linkText = x == prevPosition ? "<< prev" : x == nextPosition ? "next >>" :x;

                //        //pagingControls += "<li><a href='#' onclick='pager.showPage(" + linkToPage + "); return false;'>" + linkText + "</a></li>";
                //    }
                //}
                //else
                //{
                //    //pagingControls += "<li>" + i + "</li>";
                //}

                //if (x >= prevPosition && x <= nextPosition)
                //{

                //}
                //else
                //{
                if (count > 0)
                {
                    if (x == currentPage)
                    {
                        <a class="active-page" href="@Url.Action("Index2", "Home", new { page = x })">@x </a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index2", "Home", new { page = x })">@x </a>
                    }
                }
                // }

            }
            if (currentPage != @ViewBag.pagecount && count > 0)
            {
                var nextPage = nextPosition;
                if (nextPosition > @ViewBag.pagecount)
                {
                    nextPage = @ViewBag.pagecount;
                }
                <a href="@Url.Action("Index2", "Home", new { page = nextPage })">></a>
                <a href="@Url.Action("Index2", "Home", new { page = @ViewBag.pagecount })">>></a>
            }
        }
    </div>
</div>